const message = {
    USER_ROW_SHIP: 'Enter the row co-ordinate for your ship placement as "User"',
    USER_COL_SHIP: 'Enter the column co-ordinate for your ship placement as "User"',
    ENEMY_ROW_SHIP: 'Enter the row co-ordinate for your ship placement as "Enemy"',
    ENEMY_COL_SHIP: 'Enter the column co-ordinate for your ship placement as "Enemy"',
    ROW_ATTACKS: "Enter the row co-ordinate for your attack---",
    COL_ATTACKS: "Enter the column co-ordinate for your attack---",
    SHIP_EMPTY: 'Your ship co-ordinate values is empty "Please select co-ordinate!!!!"',
    SHIP_VALUE_WRONG: 'Your ship co-ordinate value is wrong "please enter correct co-ordinate"',
    CORRECT_ATTACK_VALUE: "Please select correct co-ordinaate for attacks",
    ENTER_ATTACK_VALUE: "Please enter co-ordinates for attack",
    VERTICAL_HORIZONTAL: 'Enter "Yes" if, you want ship vertically otherwise enter "No"',
    UP_DOWN: '"Enter "Up" if you want up side and Enter "Down" if you want down side  ',
    RIGHT_LEFT: '"Enter "Left" if you want left side and Enter "Right" if you want right side  ',
    ENEMY_BOARD: "---Enemy Board---",
    USER_BOARD: "---User Board---",
    USER_WON: "User won this game!!!",
    ENEMY_WON: "Enemy won this game!!!",
    USER_LOSS: "User you missed it!!!",
    ENEMY_LOSS: "Enemy you missed it!!!!",
    SHIP_NOT_PLACED: "Invalid value, ship can't be placed here",
    INVALI_DATTACKS: "Invalid attack value on the game board",
    LOST_CHANCE: " Lost chance !! Game Over!!!!!!!!!!!!!!!!!!! ",
    SELECT_ATTACK: "Invalid attack !!'please select correct values'",
    INVAILID_SHIP: "Invalid value for ship co-ordinate",
    DOWN_COORDINATE: "Invalid co-ordinates chosen for vertically down placing ship on game board",
    LEFT_COORDINATE: "Invalid co-ordinates chosen for horizontally left placing ship on game board",
    UP_COORDINATE: "Invalid co-ordinates chosen for vertically up placing ship on game board",
    RIGHT_COORDINATE: "Invalid co-ordinates chosen for horizontally right placing ship on game board",
}
module.exports = message;