const message = {
    ROWSHIP: "Enter the row coordinate for your ship number---",
    COLSHIP: "Enter the column coordinate for your ship number---",
    ROWATTACKS: "Enter the row coordinate for your attack---",
    COLATTACKS: "Enter the column coordinate for your attack---",
    VERTICALHORIZONTAL: "Enter whether you want to place it vertically (PRESS V) or horizontally (PRESS H)--- ",
    UPDOWN: "Enter whether you want to place the ship upside (PRESS U) or downside (PRESS D)---",
    RIGHLEFT: "Enter whether you want to place the ship left (PRESS L) or right (PRESS R) side---",
    USERONEBOARD: "USER ONE BOARD",
    USERTWOBOARD: "USER ONE BOARD",
    USERTWOWON: "User two won this game!!!",
    USERONEWON: "User one won this game!!!",
    SHIPNOTPLACED: "Invalid value, ship can't be placed here",
    INVALIDATTACKS: "Invalid attack value on the game board",
    USERTWOLOSS: "USER TWO YOU MISSED IT!!!",
    USERONELOSS: "USER ONE YOU MISSED IT!!!",
    LOSTCHANCE: " lost chance !! Game over ",
    SELECTATTACK: "invalid attack !!'please select correct values'",
    INVAILIDSHIP: "Invalid value for ship co-ordinate",
    ENTERATTACKVALUE: "please enter coordinates",
    INVAILIDCOORDINATE:"invalid co-ordinates chosen for placing ship on game board",
}
module.exports = message;